Repository planetarium/Telescope, pull requests merged in 2022-10, with the labels that each got.

#2 Search by hash feature added
  BlockChainView.cs
  Menus.cs
  WrappedBlockChain.cs
Labels: Extra Small

#3 🧹 Minor cleanup
  BlockChainView.cs
  Menus.cs
Labels: Extra Small

#5 Implemented state inspection
  Menus.cs
  WrappedBlockChain.cs
  WrappedTransacion.cs
Labels: Medium

#6 More detailed summary
  BlockChainView.cs
  Views.cs
  WrappedBlock.cs
  WrappedTransacion.cs
Labels: Extra Small

#8 ♻️ Refactor dialogs
  Gui/BlockChainView.cs
  Gui/BlockView.cs
  Gui/Dialogs.cs
  Gui/Menus.cs
  Gui/TransactionsView.cs
  Gui/Views.cs
  Menus.cs
  Program.cs
  WrappedBlock.cs
  WrappedTransacion.cs
Labels: Extra Large

#9 Added protocol version to block view
  Gui/BlockView.cs
  WrappedBlock.cs
Labels: Extra Small

#10 ♻️ Colorized block view
  Gui/BlockView.cs
  Gui/Dialogs.cs
Labels: Medium

#12 ♻️ General cleanup
  Gui/Dialogs.cs
  Gui/TransactionsView.cs
  Gui/Views.cs
  WrappedBlock.cs
  WrappedBlockChain.cs
  WrappedState.cs
  WrappedTransacion.cs
Labels: Large

#14 More elaborate transaction dialog with context
  Gui/BlockChainView.cs
  Gui/Dialogs.cs
  Gui/TransactionsView.cs
  Gui/Views.cs
Labels: Small

#15 More elaborate state dialog with context
  Gui/BlockChainView.cs
  Gui/Dialogs.cs
  WrappedBlock.cs
Labels: Small

#17 Added diff view to state view
  Gui/Dialogs.cs
  Gui/StateView.cs
  Telescope.csproj
Labels: Small

#19 Added toggle feature
  Gui/Dialogs.cs
  Gui/ToggleLabel.cs
Labels: Small

#22 Added context menu item for inspection inside transaction view
  Gui/Dialogs.cs
  Gui/TransactionsView.cs
  Gui/Views.cs
Labels: Extra Small

#23 Added scrollbar to transaction and state views
  Gui/Dialogs.cs
Labels: Extra Small

#26 Hex view added
  Gui/Dialogs.cs
  WrappedState.cs
  WrappedTransacion.cs
Labels: Extra Small

#28 Add JSON format view for transactions
  Gui/Dialogs.cs
  Telescope.csproj
  WrappedTransacion.cs
Labels: Extra Small

#29 Add json view on state view
  Gui/Dialogs.cs
  WrappedState.cs
Labels: Extra Small

#30 Add block index option `i`
  Gui/Dialogs.cs
  Program.cs
Labels: Extra Small

#35 Fix bug when searching block with hash
  Gui/Dialogs.cs
Labels: bug, Extra Small
